services:

  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: sistema-eventos-app
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/eventos
      SPRING_DATASOURCE_USERNAME: eventos
      SPRING_DATASOURCE_PASSWORD: eventos
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: sistema-eventos-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  postgres:
    image: postgres:17
    container_name: sistema-eventos-db
    environment:
      POSTGRES_DB: eventos
      POSTGRES_USER: eventos
      POSTGRES_PASSWORD: eventos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventos -d eventos"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: